chore: add notice to README
siderolabs/sidero pull request #1331
Opened 2024-03-06 16:59 UTC by andrewrynhard

2024-03-07 12:19 UTC, smira approved these changes
you can use GitHub Markdown for better representation: https://github.com/orgs/community/discussions/16925

2024-03-25 15:18 UTC, steverfrancis requested changes

2024-03-25 15:18 UTC, steverfrancis commented on README.md
> +Any and all support will be contributed by the community (including questions in our Slack workspace).
Unless you have an existing support contract covering Sidero Metal, all support will be provided by the community (including questions in our Slack workspace).

2024-03-26 03:09 UTC, frezbo commented
/m

2024-03-26 05:01 UTC, merged